version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    working_dir: /app
    command: npm run dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: senha
      DB_DATABASE: user
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./back:/app

volumes:
  pgdata:
