site_name: Documentação

nav:
  - Sobre o Projeto: "index.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
    - Ata 2: "atas-reuniao/ata-reuniao-2.md"
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"
    - Ata 4: "atas-reuniao/ata-reuniao-4.md"
    - Ata 5: "atas-reuniao/ata-reuniao-5.md"
    - Ata 6: "atas-reuniao/ata-reuniao-6.md"
    - Ata 7: "atas-reuniao/ata-reuniao-7.md"
  - Documentação:
    - Documento de Visão: "Visao_do_Produto_e _projeto_de_escopo.md"
    - Documento de Arquitetura: "Arquitetura.md"

theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.highlight
